springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /openapi.yaml
    path: /api-docs

spring:
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/polik
    username: polik
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
  cache:
    cache-names: shop-units
    caffeine:
      spec: maximumSize=5000,expireAfterAccess=60s

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 80